# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: external-dns-adguard
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.0
        env:
          - name: ADGUARD_URL
            value: "${ADGUARD_URL}"
          - name: ADGUARD_USER
            value: "${SECRET_INTERNAL_ADGUARD_USER}"
          - name: ADGUARD_PASSWORD
            value: "${SECRET_INTERNAL_ADGUARD_PASS}"
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          successThreshold: 1
    extraArgs:
      - --ignore-ingress-tls-spec
    policy: sync
    registry: noop
    interval: 30m
    triggerLoopOnEvent: true
    sources:
      - ingress
    domainFilters: ["${SECRET_DOMAIN}"]
