---
version: "3"

vars:
  _SYS_PYTHON_BIN: python3
  VENV_PATH: "{{.ROOT_DIR}}/.venv"
  _VENV_PYTHON: "{{.VENV_PATH}}/bin/python"
  CLUSTER_DIR: "{{.ROOT_DIR}}/cluster"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  VIRTUAL_ENV: "{{.VENV_PATH}}"

includes:
  precommit: .taskfiles/PrecommitTasks.yml
  sops: .taskfiles/SopsTasks.yml
  venv: .taskfiles/VenvTasks.yml
  tf: .taskfiles/TerraformTasks.yml
  cluster: .taskfiles/ClusterTasks.yml

tasks:
  default:
    cmd: task --list
    silent: true

  init:
    desc: Initialize all components and install required tools with Brew
    cmds:
      - task: venv:init
      - task: precommit:init
      - task: tf:init
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        direnv
        sops
        hashicorp/tap/terraform
        tflint

  install-helm-apps:
    desc: Bootstrap core apps needed for Talos
    dir: "{{.ROOT_DIR}}/bootstrap"
    cmds:
      - until kubectl wait --for=condition=Ready=False nodes --all --timeout=600s; do sleep 10; done
      - helmfile --file helmfile.yaml apply --skip-diff-on-install --suppress-diff
      - until kubectl wait --for=condition=Ready nodes --all --timeout=600s; do sleep 10; done
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.ROOT_DIR}}/kubeconfig
      - msg: Missing helmfile
        sh: test -f helmfile.yaml
