---
version: "3"

vars:
  _SYS_PYTHON_BIN: python3
  VENV_PATH: "{{.ROOT_DIR}}/.venv"
  _VENV_PYTHON: "{{.VENV_PATH}}/bin/python"
  CLUSTER_DIR: "{{.ROOT_DIR}}/cluster"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  VIRTUAL_ENV: "{{.VENV_PATH}}"
  TALOSCONFIG: "{{.ROOT_DIR}}/talosconfig"

includes:
  precommit: .taskfiles/PrecommitTasks.yml
  sops: .taskfiles/SopsTasks.yml
  venv: .taskfiles/VenvTasks.yml
  tf: .taskfiles/TerraformTasks.yml
  cluster: .taskfiles/ClusterTasks.yml
  talos: .taskfiles/TalosTasks.yml

tasks:
  default:
    cmd: task --list
    silent: true

  init:
    desc: Initialize all components and install required tools with Brew
    cmds:
      - task: venv:init
      - task: precommit:init
      - task: tf:init
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        direnv
        sops
        hashicorp/tap/terraform
        tflint

  hack:shell:
    desc: Start a privileged ubuntu pod and shell into it
    cmds:
      - kubectl apply -f {{.ROOT_DIR}}/hack/ubuntu-pod.yaml
      - kubectl wait pod --for=condition=Ready=True ubuntu-shell
      - kubectl -n default exec -it ubuntu-shell -- bash
      - kubectl delete pod ubuntu-shell
    interactive: true
    preconditions:
      - msg: Missing ubuntu pod file
        sh: test -f {{.ROOT_DIR}}/hack/ubuntu-pod.yaml
      - msg: Missing kubectl
        sh: which kubectl
