---
version: "3"

vars:
  _SYS_PYTHON_BIN: python3
  VENV_PATH: "{{.TASKFILE_DIR}}/.venv"
  _VENV_PYTHON: "{{.VENV_PATH}}/bin/python"
  CLUSTER_DIR: "{{.ROOT_DIR}}/cluster"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  precommit: .taskfiles/PrecommitTasks.yml
  sops: .taskfiles/SopsTasks.yml
  venv: .taskfiles/VenvTasks.yml
  tf: .taskfiles/TerraformTasks.yml
  cluster: .taskfiles/ClusterTasks.yml

tasks:
  default:
    cmd: task --list
    silent: true

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - task: venv:init
      - task: precommit:init
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        direnv
        sops
        hashicorp/tap/terraform
        tflint
