# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/core/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cert-manager-issuers
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
    - name: reflector
  path: ./cluster/core/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
