# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 30m
  chart:
    spec:
      chart: k8up
      version: 4.8.4
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    metrics:
      serviceMonitor:
        enabled: true
      grafanaDashboard:
        enabled: true
        additionalLabels:
          - grafana_dashboard: '1'
    k8up:
      skipWithoutAnnotation: true
      envVars:
        - name: BACKUP_GLOBALS3BUCKET
          valueFrom:
            secretKeyRef:
              name: k8up-secrets
              key: global-bucket
        - name: BACKUP_GLOBALACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: k8up-secrets
              key: global-key
        - name: BACKUP_GLOBALSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: k8up-secrets
              key: global-key-secret
        - name: BACKUP_GLOBALS3ENDPOINT
          valueFrom:
            secretKeyRef:
              name: k8up-secrets
              key: global-endpoint
