apiVersion: v1
kind: Secret
metadata:
    name: k8up-secrets
stringData:
    global-bucket: ENC[AES256_GCM,data:nbk3QhmIKpM8HxqHnMaK,iv:BbnHF9CtM2I5riMTslXy366hbzXBqczAv0zYNI7QXXg=,tag:xYmNOsQy4ups+11T3Kj71w==,type:str]
    global-key: ENC[AES256_GCM,data:pITZLHh8xrtPaZ9fv8F+I5TJz/8=,iv:2w+EOj572GOxP4abfUZX1uLH4cRpJgqlBswI6M+Iir0=,tag:MDt5ahh3SxMLTvt7/wh4Dg==,type:str]
    global-key-secret: ENC[AES256_GCM,data:Pojv4vn/aaBebTLG9loVZVfjoe4vfjx8kZhWqlBTjgXCM829KI+RyQ==,iv:L5SXvo2DKbq7p3E5Dir2HUNaIRQ9xcPVWjgolOlfyRM=,tag:AAygUIMLLUyIvdBEowfv5g==,type:str]
    global-endpoint: ENC[AES256_GCM,data:xZFvliKmfsYgJ7qfh7Xlc5+O7Q==,iv:LJkikErKSMiDywWJyZ7arqzcH1Dr6faIzInMtYJgVCs=,tag:puqQhrAM8LtcZBqHaM9e0w==,type:str]
    global-repo-password: ENC[AES256_GCM,data:gNTXwrjAgb/HyQafwvza5gL1Oto=,iv:LUQhqgEpz2t0KHKjP9CDUBbsk3g+YeMPzOPkGtfiD0c=,tag:ZGO4HMaplSYY5IeJFISglg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYVRHY281Ym1JaXk0c1Bt
            TjJoTURzN2dlc1I4NU05ODREQzlsbDNJOUdBClQ3VS90UDhBeTJxSTZxL1dSRkd4
            STd5OUp1K3NnSWs0OUVzL2EzMy9nMmsKLS0tIE8zaGFNRGpDbm9EQTBQaENvTVRn
            M1dHREYwOFVZU3VtSEl0aUpxNEFjUUEKV8iqn3qXiINXa+2d5bTOYtmHmCDMmm9Y
            KT/fE79l+ExFDNWj9TTKJQT6EF/I35+CJZSMjNjIDTq4+t2p7jty7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T21:30:44Z"
    mac: ENC[AES256_GCM,data:3L3k3ivt9881s68GtZulYshTSRnz0gwmxbaixDz/mnEenaFkvKnzyWB3YSXxq4bwhD9l6bvPhT6dsfUWJR59BcNx2iFFPniMNAMkPCRBe38xgEHsac+SiwgXOFY3YqlaSqY17inIlIbGXxtzxWF7Vbyuy97uGRDTccLELhIUqTo=,iv:QQC8M88Q7cvu+IEh38gDkc6FP1IWztjkqMJh6W4T7x4=,tag:U+ukrxev1IG5/LD1bldk5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
