apiVersion: v1
kind: Secret
metadata:
    name: k8up-secrets
stringData:
    global-bucket: ENC[AES256_GCM,data:upzzRA==,iv:+1J8IhRN7iOPe+oaPn5MXeQLoAlSXfg6R1Dqrg6xjYY=,tag:uFWP3cLxSg7IDnu2HZ+JyA==,type:str]
    global-key: ENC[AES256_GCM,data:pITZLHh8xrtPaZ9fv8F+I5TJz/8=,iv:2w+EOj572GOxP4abfUZX1uLH4cRpJgqlBswI6M+Iir0=,tag:MDt5ahh3SxMLTvt7/wh4Dg==,type:str]
    global-key-secret: ENC[AES256_GCM,data:Pojv4vn/aaBebTLG9loVZVfjoe4vfjx8kZhWqlBTjgXCM829KI+RyQ==,iv:L5SXvo2DKbq7p3E5Dir2HUNaIRQ9xcPVWjgolOlfyRM=,tag:AAygUIMLLUyIvdBEowfv5g==,type:str]
    global-endpoint: ENC[AES256_GCM,data:eTGHmwyFJPyJfhNTYD+9fg==,iv:pmZtHPuBeu1wfE+phEv61jrRe/YDEyTC8hjIG9W+cXk=,tag:1Sisgpidvi6vFyTkMfKy6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYVRHY281Ym1JaXk0c1Bt
            TjJoTURzN2dlc1I4NU05ODREQzlsbDNJOUdBClQ3VS90UDhBeTJxSTZxL1dSRkd4
            STd5OUp1K3NnSWs0OUVzL2EzMy9nMmsKLS0tIE8zaGFNRGpDbm9EQTBQaENvTVRn
            M1dHREYwOFVZU3VtSEl0aUpxNEFjUUEKV8iqn3qXiINXa+2d5bTOYtmHmCDMmm9Y
            KT/fE79l+ExFDNWj9TTKJQT6EF/I35+CJZSMjNjIDTq4+t2p7jty7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-01T20:50:47Z"
    mac: ENC[AES256_GCM,data:t278lF7NBc7Ej3pz8lYREKEzJNSFeboK50wv19PEbkkvnsFQJtXFhSlV2XQQ29MbjKZoWJvRS9tqabvTQ1pc7WcOyyoDYpAD59Y4NsFYbnUOlvdkM52YnWI3VvQbG+dtjs+gG+qqf0I/rvkwYqPp3JTSuSN0c8l/vmBdUjKMb4w=,iv:peVQkYCLwcaYf1+49xY2+aQdRsUsEOOWinXId4X8dqI=,tag:AL3g8ITm62yoOvRQ/H26aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
