---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Bucharest
  ADGUARD_URL: "http://192.168.0.5"
  STORAGE_NAS_IP: "192.168.0.111"
  STORAGE_NAS_MEDIA_PATH: "/volume1/media"
  NIGNX_INGRESS_IP: "192.168.1.25"
  PROXMOX_CSI_URL: https://192.168.0.201:8006/api2/json
  PROXMOX_CSI_REGION: homelab
  PROXMOX_CSI_STORAGE_ID: nvme-ssd
