---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Bucharest
  ADGUARD_URL: "http://dns.internal/"
  STORAGE_NAS_IP: "192.168.0.111"
  STORAGE_NAS_MEDIA_PATH: "/volume1/media"
  NIGNX_INGRESS_IP: "192.168.1.25"
