apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: cert-manager,kube-system,monitoring
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aUUeOaeLTDA=,iv:unA5bafXcqzK66gfE4wbjLEeKlhuZUAWMR2VMXVoHEM=,tag:43R4m+oWuAFhRqAwjOsKcg==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:91HXMnrcZzw0VkEhKQ==,iv:iorhTlO0HJUjgwlwCDUpBqs5hjHILzh2J2HIghlBa00=,tag:VIqI5RH6jUuuPo+YXlUcPA==,type:str]
    SECRET_PROM_DISCORD_WH_URL: ENC[AES256_GCM,data:AyN08APIVVM/X78z+PAEf3pzmCwYyQRpINpxakBXKhmVtdiXjw2TUeSSLrxT6jCP+1I81HgJks6o6p7qlwWerhFAvYqbuRj6vmLDGR7NmEbgTlQMw9dXxhStMyAWm7OntLtbSdXs3eT6Db1EqeZtylujquot4xSVhA==,iv:XY5rNoOr+bJSVKvvBkOxJawksuPLXuRWkEWIGQruUdE=,tag:5N4V5RJm6VBQ9YB+t5H9DQ==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:TanXvy/RmGikPv788nOF,iv:D/a4BrkqlD31Tnf0Xq1hYSyHgHJaBZDQnupTu02Mh0Y=,tag:4oXemIC31o+2KCg7Bb1SEA==,type:str]
    SECRET_INFLUXDB_ADMIN_PASS: ENC[AES256_GCM,data:WFpC5vfUa4kjLt+HQxPUTmf5,iv:+k8cInEzmbAcJ099OJrd4LP/Ru9DMFLoLN2mP6Mo++A=,tag:kqIGwmXQwsRyvJQYaqjT5w==,type:str]
    SECRET_INFLUXDB_ADMIN_TOKEN: ENC[AES256_GCM,data:8GUwlqTNDXW2Mw2lOQy+PXLxaU15+wwckyA=,iv:3wSGoGlmxArrtCjYNXpK4aizlXtMRE5606ZCOhiGsoM=,tag:7SKq71iIXzhEs9gl9ah4Ow==,type:str]
    SECRET_INTERNAL_ADGUARD_USER: ENC[AES256_GCM,data:Xm5fy7Gcrg==,iv:HgAuBtvxKq7mEu+L0lZY86KEkAV4e6X+Fe2fnDe2N+s=,tag:pmeeQ+UGXBta4Zd9UkoZ4Q==,type:str]
    SECRET_INTERNAL_ADGUARD_PASS: ENC[AES256_GCM,data:GMCLQVwE3zEI1BAbdewBGb9TwhY=,iv:MUJfbvsDs2pl+rHR58IiwfcywSQERfhRcSwvsu7X9ss=,tag:S/CH4fxHpE8n06HgpW7Uug==,type:str]
    #ENC[AES256_GCM,data:Ca0pNi8Xw6/htjcQLLM=,iv:fISmlFnSZmkPIyDkqAQ+EqynJ7QU6zCxJ4TAeFJOY1c=,tag:YIl+85Ze+Fy1i134QeLyQg==,type:comment]
    GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:Tmm1O9nP,iv:Wn0muevVhijSNP8NuuiAL1E66yMcMuHyeuHpsaQMRGQ=,tag:gmRI+F4SBNK1aS+VQyarGA==,type:str]
    GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:iRl/pZJHWJqA6l56k0DHxqmDOyBhZntonBmdewgOXsVHcb+FNhsfTA==,iv:o0EpYFgBEsfKGXTco6aT4Q7xBPFDqaPGuaT7rDzgmyE=,tag:UnSx8/agboddKI54wgZ7Zw==,type:str]
    #ENC[AES256_GCM,data:bDMSF5p1QIdt0Li88IIGezP6,iv:dO/EvLV0ovaHywKGaiMvRvGoJokosheCOzuy8YvR2ko=,tag:v+I6FrWaU7f8O1jiFSbAKQ==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:byK+8KieF73gy7dMXeMwQ7uo09dOlfL2V3XudF7eNoHlnQUU+t1nCFjgQsUOQ58Svp4=,iv:Rg+nU5ivjpcUYgxfR0LcGX+bM6PdMx/+DA0q2md5nFY=,tag:/TpOmklqj7zOBAQmCN70kA==,type:str]
    AUTHENTIK_EMAIL_HOST: ENC[AES256_GCM,data:yZTKwFwOBJvsDyPtU//meyQUHrA=,iv:3KVpIh1CgeTLoEl0A9GcLuqKYBQqPt60yH3ZBklpxBo=,tag:CPpW5SUuok29Ig3YMqBi/A==,type:str]
    AUTHENTIK_EMAIL_PORT: ENC[AES256_GCM,data:pFoc,iv:lsZ9Q5fh7ECXX0BTVtG5cMFiZ/TObB45RzQgIP7VEag=,tag:P0Z8l453u7vZtuuAUYK6yw==,type:str]
    AUTHENTIK_EMAIL_USERNAME: ENC[AES256_GCM,data:ZC1dH1tK3jKE2oYvPIz1VEzaiLRwAmU=,iv:EEJs/3+Kwh1yVDtiXjCHR0cBtiwfmgeFdGCTyvcx2LU=,tag:PfMvPVXcl5yX3j8xs+IlyA==,type:str]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:5PH0jaA1mNowPe5OsDDhisin,iv:k6ZD3webTlhl+fQU8NgrjxdVsn37yTvUljAoc85+w3Y=,tag:wjpxhWsBU0irXbOziqTwVQ==,type:str]
    AUTHENTIK_EMAIL_USE_TLS: ENC[AES256_GCM,data:UzWui90=,iv:X19mooxFmbOmleUgnir8zkSrACWOHi2wAqnq18qDdn0=,tag:zH+EzLipXqJJU+jBbme1Ew==,type:str]
    AUTHENTIK_EMAIL_USE_SSL: ENC[AES256_GCM,data:t95PbA==,iv:LRT1s2zcKZg9mFvMNRpd4pdc4RRKHLGT+NJmc1GK+Hk=,tag:I1QKyLZCWB7xckmxcxetPg==,type:str]
    AUTHENTIK_EMAIL_TIMEOUT: ENC[AES256_GCM,data:aHY=,iv:H27de8IF8vnUU7PR5KEzbY7YTQMEAG9IiccCh//bhEg=,tag:DQl29makx7lgVP2p3BBIuQ==,type:str]
    AUTHENTIK_EMAIL_FROM: ENC[AES256_GCM,data:g0GbGlhjFI7/asXlvPhu4wawHnjjizc=,iv:5iSXoyM7Honn0jdsFMGDMGJgEZCGTf0Yj8SGoS/v2zc=,tag:VwsSZuWWcA7QOuSt3V8P+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RVdEaDl3RzlvRTlrYk05
            NGdnU2czbnFyNGJSYnZOdzV6TEtTRG10ZGdvCmV6WEQ0NWF3T1lmWW1PME5Hc25F
            TUxzck1mcFBsN0l3WmlPZXRTcE9ZcWsKLS0tIHh3Y01qaG12WEM3T2lGdlVtbkYr
            elFHU0ZreTRJa1V6ZnhKd0lUMlVVV2cKHvyb635NOW3RijhtUWm74n1FAX5vLTlw
            D1DKMLRDlceQzW2J6a4YlJBMAkw0KgOn/kJlvPdYWjzkV0TN8wTvWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T12:04:13Z"
    mac: ENC[AES256_GCM,data:tphHanerhdI/sVRUS4Eb8Gzef7adbRCtHhOf3UgrQFlFZODWtc7WexRTQfgPmMCDkjJCBKE+YLx7L1L1PyuwJ7mfkTUBQEjQNtPkArCHW9ABYWQjmdLjEHdI6Kjnxp82AQ82ifFuSVTOvMC+TPTczOBig5sPf3kSMPG51bQubdE=,iv:1+uxU5kp525i5DyUBirie2vHylJahvA3NKd9Vt7hsIo=,tag:obYNVG1L19V2Q+Sk4kll/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
