# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    obs:
      callhome:
        enabled: false
    eventing:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
    mayastor:
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        localpvScConfig:
          basePath: /var/mnt/storage/openebs/etcd
      loki-stack:
        localpvScConfig:
          basePath: /var/mnt/storage/openebs/loki
    localpv-provisioner:
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: /var/mnt/storage/openebs/local
