# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synology-csi
  namespace: flux-system
spec:
  targetNamespace: synology-csi
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/core/synology-csi/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
