# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: alertmanager
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    fullnameOverride: alertmanager
    replicaCount: 1

    config:
      global:
        resolve_timeout: 5m
      inhibit_rules:
        - source_matchers:
            - 'severity = critical'
          target_matchers:
            - 'severity =~ warning|info'
          equal:
            - 'namespace'
            - 'alertname'

        - source_matchers:
            - 'severity = warning'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
            - 'alertname'

        - source_matchers:
            - 'alertname = InfoInhibitor'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: discord
        routes:
          - receiver: 'null'
            matchers:
              - 'alertname =~ InfoInhibitor|Watchdog'
      receivers:
        - name: 'null'
        - name: discord
          discord_configs:
            - webhook_url: ${SECRET_PROM_DISCORD_WH_URL}
              title: |-
                [{{ .Status | toUpper }}:{{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else }}{{ .Alerts.Resolved | len }}{{ end }}]
              message: |-
                {{- range .Alerts }}
                  **{{ .Labels.alertname }} {{ if ne .Labels.severity "" }}({{ .Labels.severity | title }}){{ end }} **
                  {{- if ne .Annotations.description "" }}
                    **Description:** {{ .Annotations.description }}
                  {{- else if ne .Annotations.message "" }}
                    **Message:** {{ .Annotations.message }}
                  {{- else if ne .Annotations.summary "" }}
                    **Summary:** {{ .Annotations.summary }}
                  {{- else }}
                    **Description:** N/A
                  {{- end }}
                {{- end }}
      templates:
        - '/etc/alertmanager/config/*.tmpl'

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: &host alertmanager.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - *host

    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
      size: 50Mi
