# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql-operator
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    envs:
      k8sClusterDomain: cluster.local
