# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    clientInfoSecret:
      clients:
        - host: ${STORAGE_NAS_IP}
          https: false
          password: ${SECRET_SYNO_PASS}
          port: 5000
          username: ${SECRET_SYNO_USER}
      create: false
    storageClasses:
      synology-csi-delete:
        parameters:
          dsm: ${STORAGE_NAS_IP}
          fsType: ext4
          location: /volume2
          protocol: iscsi
      synology-csi-retain:
        isDefault: true
        parameters:
          dsm: ${STORAGE_NAS_IP}
          fsType: ext4
          location: /volume2
          protocol: iscsi
