---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-age
