# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mysql
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/apps/databases/mysql/operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mysql-instances
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: mysql
    - name: proxmox-csi
  path: ./cluster/apps/databases/mysql/instances
  prune: false
  sourceRef:
    kind: GitRepository
    name: cluster-repo
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
