# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    longhornUI:
      replicas: 1
    monitoring:
      enabled: true
      createPrometheusRules: true
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
      recurringJobSelector:
        enable: false
    defaultSettings:
      orphanAutoDeletion: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      fastReplicaRebuildEnabled: true
      removeSnapshotsDuringFilesystemTrim: true
      v1DataEngine: true
      v2DataEngine: false
      allowCollectingLonghornUsageMetrics: false
      freezeFilesystemForSnapshot: enabled
      autoCleanupSnapshotWhenDeleteBackup: true
      rwxVolumeFastFailover: true
      defaultDataPath: /var/mnt/storage/longhorn
      backupTarget: "nfs://${STORAGE_NAS_IP}:/volume2/cluster-backups"
      defaultLonghornStaticStorageClass: "longhorn"
