# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    kind: Deployment
    deschedulingInterval: 30m
    deschedulerPolicy:
      profiles:
        - name: Main
          pluginConfig:
            - name: "LowNodeUtilization"
              args:
                thresholds:
                  "memory": 20
                targetThresholds:
                  "memory": 70
            - name: "RemovePodsHavingTooManyRestarts"
              args:
                podRestartThreshold: 30
                includingInitContainers: true
                states:
                  - CrashLoopBackOff
            - name: "RemoveDuplicates"
            - name: "RemovePodsViolatingNodeAffinity"
              args:
                nodeAffinityType:
                  - "requiredDuringSchedulingIgnoredDuringExecution"
          plugins:
            balance:
              enabled:
                - "LowNodeUtilization"
                - "RemoveDuplicates"
            deschedule:
              enabled:
                - "RemovePodsHavingTooManyRestarts"
                - "RemovePodsViolatingNodeAffinity"
    service:
      enabled: true
    serviceMonitor:
      enabled: true
